### ISSUE TITLE
Can you give where you got the dependencies?

### ISSUE THREAD

**Issue by rowetechinc** [gblmarquez/mui-sample-chat#1]
Not sure where you got some of the dependencies.  Can you list where you got them?

**Comment by gblmarquez** [comment]
@rowetechinc I enable NuGet package restore and removed uncessary dependencies, I just commit. Make it try if works for you we can close this.

**Comment by rowetechinc** [comment]
I cannot get the Fepin.Foundation dll.  Since it looks like you are the owner, i put it here.   I hope the Matrix reference is apart of Fepin.Foundation, if not, then i am not sure where to find the Matrix reference.

PM> Install-Package Fepin.Foundation
Install-Package : Unable to find package 'Fepin.Foundation'.
At line:1 char:16
- Install-Package <<<<  Fepin.Foundation
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

PM>

**Comment by gblmarquez** [comment]
I removed this library from the packages.config, sorry for that.

**Comment by rowetechinc** [comment]
You removed the Matrix reference but you still heavily use it in ChatViewModel.

**Comment by gblmarquez** [comment]
I was using the GitHub Edit, but I didnt realize that. Is it ok now?

**Comment by rowetechinc** [comment]
Works now.
Like the settings options.

**Comment by gblmarquez** [comment]
Sorry for my mistakes.
Do you use Skype?
